### ISSUE TITLE
C Stdlib is not automatically rebuilt when changed

### ISSUE THREAD

**Issue by krtab** [OCamlPro/owi#117]
Changing for example `stdlib.c` should mark the compiled stdlib to be obsolete and cause it to be rebuilt when `dune build` is invoked.

Similar to #111

**Comment by zapashcanon** [comment]
I have to investigate https://discuss.ocaml.org/t/dune-how-to-add-a-dependency-on-one-executable-to-another/5959/10 to see if the situation can be improved
