### ISSUE TITLE
some symbolic instructions are failing

### ISSUE THREAD

**Issue by zapashcanon** [OCamlPro/owi#120]
see:

https://github.com/OCamlPro/owi/pull/96#discussion_r1452692529
https://github.com/OCamlPro/owi/pull/96#discussion_r1452692882
https://github.com/OCamlPro/owi/pull/96#discussion_r1452693000

**Comment by epatrizio** [comment]
After #151 PR, instructions have been implemented.
However, it remains (non-exhaustive, in actual scope) : 
- `f32.copysign` https://github.com/OCamlPro/owi/blob/4e3a35f73a74b826f0fcfc25f0551296ca110de1/test/sym/binop_f32.wat#L39
- `f64.copysign` https://github.com/OCamlPro/owi/blob/4e3a35f73a74b826f0fcfc25f0551296ca110de1/test/sym/binop_f64.wat#L39
- `f32.trunc` https://github.com/OCamlPro/owi/blob/4e3a35f73a74b826f0fcfc25f0551296ca110de1/test/sym/unop_f32.wat#L35
- `f64.trunc` https://github.com/OCamlPro/owi/blob/4e3a35f73a74b826f0fcfc25f0551296ca110de1/test/sym/unop_f64.wat#L35

**Comment by zapashcanon** [comment]
cc @filipeom, I believe these are the last (hopefully) missing instructions in encoding :sweat_smile:

**Comment by filipeom** [comment]
I think I added `trunc`, `copysign` can probably be implemented without an encoding operator. I can take a look at these when I get more free time :smiley:

**Comment by zapashcanon** [comment]
@epatrizio could you do a PR where you re-enable the `trunc` tests then ? :)

**Comment by zapashcanon** [comment]
Thanks! Do you want to try implementing copysign in Owi directly too ? This should not be too hard.

**Comment by zapashcanon** [comment]
This has actually been fixed, thanks @epatrizio ! :)

@filipeom, for now `copy_sign` is implemented in Owi, if you think it would make sense to have it directly in encoding, feel free to copy-paste the implementation (and to patch Owi to use the one from encoding :-)).
