### ISSUE TITLE
Killing owi c doesn't kill owi sym

### ISSUE THREAD

**Issue by krtab** [OCamlPro/owi#129]
Run `dune exec owi -- c test/owic/stdlib/malloc_aligned.c`, ctrl-c it before it finished, the `owi sym` process remains alive.

(You may need to test on a c file that does an infinite loop to have time to crtl c it)

**Comment by zapashcanon** [comment]
Haha, this one should not be too hard to fix if you are interested.

In `cmd_c.ml` you have a function `let owi ..` that calls `owi sym` directly through a command instead of using the appropriate module. This is a leftover from when they were in a separate binary.
