### ISSUE TITLE
Deploy CI is failling because of incoherent caching

### ISSUE THREAD

**Issue by krtab** [OCamlPro/owi#220]
The `deploy` CI is currently failing. My investigation so far have led me to the following conclusion.

- A fresh run without caching works fine. 
- A run with a cache hit will fail because during the coverage generation, `libc.wasm` is not found.

What I currently don't have a good explanation for:
- Testing depending on `libc.wasm` is also done in our `build` CI. However, this one doesn't fail because of cache hits. My guess is that somehow, because of `bisect`, the `dune runtest` does not manage to detect that `libc.wasm` is missing after a successful cache hit and does not rebuild it.

**Comment by zapashcanon** [comment]
It seems to be solved
