### ISSUE TITLE
new test not passing: unexpected token "\"(func (export \"f1\") (result i32)\""

### ISSUE THREAD

**Issue by zapashcanon** [OCamlPro/owi#278]
After #276:

```shell-session
$ owi script --no-exhaustion reference/comments.wast
unexpected token "\"(func (export \"f1\") (result i32)\""
[40]
```

This is related to UTF-8 definition of newline, see https://github.com/WebAssembly/spec/commit/43d405f5301adefb823b443c6fb9bb6093b1e1a7

**Comment by epatrizio** [comment]
here's a minimalist test :
```wast
(module quote
  "(func )"
)
```

**Comment by epatrizio** [comment]
```wast
(module quote
  "(func"
  "  ;; comment\0a"
  ")"
  "(func"
  "  ;; comment\0d"
  ")"
  "(func"
  "  ;; comment\0d\0a"
  ")"
)
```
there may be 2 different problems because the first minimalist example does not mention `newline` character ... ?!

**Comment by krtab** [comment]
> here's a minimalist test :
> 
> ```webassembly
> (module quote
>   "(func )"
> )
> ```

I'm opening a issue (and trying a fix) for this one.
