### ISSUE TITLE
Typechecking problem ?

### ISSUE THREAD

**Issue by epatrizio** [OCamlPro/owi#29]
This program is not correctly typed but when it is executed with Owi, the error is detected during the interpretation.
Typechecker should intercept it before ?
```wast
(module
  (start 0)
  (func
    i32.const -1
    i64.const 0
    i32.const 1
    (if  (param  i32) (param  i64)
      (then
        f32.reinterpret_i32
        drop
        drop
      )
      (else
        drop
        drop
      )
    )
  )
)
```

**Comment by zapashcanon** [comment]
Thanks ! You may want to add this the test in [0902878](https://github.com/OCamlPro/owi/commit/090287833ae6ab1b47e902eca9ed9a616bcaee17) in the reference interpreter ?
