### ISSUE TITLE
memarg align pretty printer

### ISSUE THREAD

**Issue by epatrizio** [OCamlPro/owi#42]
```ocaml
let memarg [...] =
  [...]
  Format.fprintf fmt "offset=%d align=%d" offset align
```
_(types.ml - line 532)_
`align` should be interpreted as a power of 2 _(2^align)_

**Comment by zapashcanon** [comment]
@epatrizio this was fixed, right ?

**Comment by epatrizio** [comment]
yes, I think so :thinking: 
https://github.com/OCamlPro/owi/blob/0035201093f0c2dc1031fc86e7c273b531d73261/src/types.ml#L208
```ocaml
let pp_memarg =
  let pow_2 n =
  (* ... *)
  pp fmt "%aalign=%ld" pp_offset offset (pow_2 align)
  (* ... *)
```

**Comment by zapashcanon** [comment]
Let's close then. :)
