### ISSUE TITLE
Bug optimize module

### ISSUE THREAD

**Issue by epatrizio** [OCamlPro/owi#43]
```wast
(module $m
  (start 0)
  (func $start   
    call $f
  )
  (func $f (local i32) (local i32) (local i32) (local i32)
    i32.const 0
    local.set 3
  )
)
```
This module is correct, but its interpretation after optimization launches this error :
`owi: internal error, uncaught exception: Invalid_argument("index out of bounds")`
Owi stack trace (debug mode) displays : `local.set 1` instead of `local.set 0`
Only locale `id:3` is used, so it must become `id:0` after optimization.

**Comment by epatrizio** [comment]
Compute of local var indexes still in use could not be done recursively.
Thanks @zapashcanon for refactoring

**Comment by zapashcanon** [comment]
Could you add this test to the various `optimize` test ?
