### ISSUE TITLE
Typing error

### ISSUE THREAD

**Issue by epatrizio** [OCamlPro/owi#45]
```wast
(module $m
  (start 0)
  (func $start
    ;; 1. OK Owi / KO! Official interpreter
    i32.const 1
    i64.const 2
    ;; 2. KO! Owi / OK Official interpreter
    ;; i64.const 2
    ;; i32.const 1
    (if  (param  i64) (param  i32)
      (then
        drop
        drop
      )
      (else
        drop
        drop
      )
    )
  )
)
```
This module seems to be correct in Owi but this error is launched with official wasm interpreter :
`type mismatch: instruction requires [i64 i32 i32] but stack has [i32 i64 i32]`
The behavior is reversed in case 2 (see comment 2).

**Comment by zapashcanon** [comment]
Fixed in c3888b17468e32bc3be8429a309ab4d9d8f99b41.
