### ISSUE TITLE
Type checking error

### ISSUE THREAD

**Issue by epatrizio** [OCamlPro/owi#48]
```wast
(module $m
  (func $f0 (result f32)
    f32.const 0
    f64.const 0
    i32.const 0
    (if
      (then
      )
    )
    f32.demote_f64
    drop
  )
)
```
Owi launches this error : `type mismatch (pop) requires [f64] but stack has [f32 f64]`
while everything is ok with the official interpreter

**Comment by zapashcanon** [comment]
It was almost the same as #45, it should be fixed for real this time in f44c55fa3564d2ba15b955391ba176061df9c13f.
