### ISSUE TITLE
life game examples seem to be broken

### ISSUE THREAD

**Issue by zapashcanon** [OCamlPro/owi#90]

**Comment by epatrizio** [comment]
Initial analysis : 
- life game _web_ is OK
- life game _console_ and _graphics_ are **KO** (`Fatal error: exception Not_found`)
Life game example is broken !

The _web_ version is based on 1 `wasm` module.
The _console_ and _graphics_ versions is based on 2 `wasm` modules.
The link between the `life` and `life_loop` modules seems broken.
Further deeper research is now required :
```ocaml
module_to_run = Compile.until_link link_state [...]
```
```ocaml
Interpret.Concrete.modul link_state [...]
```

**Comment by epatrizio** [comment]
Here's a minimalist example that reproduces the bug :
```wast
;; m1.wast (function export)
(module
  (func $42 (export "42") (result i32)
    i32.const 42
  ))
```
```wast
;; m2.wast (function import)
(module
  (import "m1" "42" (func $42 (result i32)))
  (func $start
    call $42
    drop
  )
  (start $start)
)
```
The related OCaml code (m1 and m2 Linking) is the same as
(without `extern_module`)

**Comment by epatrizio** [comment]
This bug is still present.
The `Not_found` exception is triggered here
https://github.com/OCamlPro/owi/blob/d17beb336045b84d6b4d6a860965c96d08ac2ac2/src/interpret.ml#L1491
Maybe `link_state` is broken via successive `Compile.until_link` calls ?

**Comment by epatrizio** [comment]
`git bisect` has just helped me ;)
OK > Jul 30, 2023 commit https://github.com/OCamlPro/owi/commit/3d2b22a1c28b0043c53d1cdec31472f42f151f43
KO > Sep 10, 2023 commit https://github.com/OCamlPro/owi/commit/dcccd94cd420da952c75793a9427c27dc241ba25
I now propose to try to fix the bug ...

**Comment by zapashcanon** [comment]
I'm quite surprised, this commit has nothing to do with the interpreter. Did you bisect fully ? There was no commit between Jul 30 and Sep 10 ?

**Comment by epatrizio** [comment]
Sorry, I made a mistake: the commits are on different branches. I continue ...

**Comment by epatrizio** [comment]
`git bisect` better analysis : 
OK > https://github.com/OCamlPro/owi/commit/56562eb30083c8deaaeb27586ac11cc4887d8217
KO > https://github.com/OCamlPro/owi/commit/19d3f1d1d45e44b1cca3f2e6232297ebed806f92

**Comment by zapashcanon** [comment]
I'm still surprised by this bisect result TBH

**Comment by filipeom** [comment]
There is no bug with owi's linking system; it's about how the modules are actually linked. When the link state of `life_loop.wat` is connected with the previous link state, the result is ignored.

https://github.com/OCamlPro/owi/blob/8a9f5a0b8ec7db7ac12c01125b82933b31c80550/example/define_host_function/life_game/life_graphics.ml#L98-L104

Simplify change this to:

```ocmal
let module_to_run, link_state =
  match
    Compile.until_link link_state ~unsafe:false ~optimize:true ~name:None
      pure_wasm_module_2
  with
  | Error e -> Result.failwith e
  | Ok (m, state) -> m
```

**Comment by filipeom** [comment]
> You're right @filipeom ;) I went in the wrong (deep and complex) direction, while the fix was obvious. But I discovered `git bisect`, cool!

I think that the 'bug' label and the fact that it was exploding might have contributed to a state of confirmation bias. It happened to me as well :sweat_smile:

**Comment by zapashcanon** [comment]
Yes we actually discovered the issue yesterday too after spending quite some time on it haha
