### ISSUE TITLE
Unsupported symbolic value reasoning \"(++ symbol_0 (++ symbol_0 (++ symbol_0 symbol_0)))\"")

### ISSUE THREAD

**Issue by krtab** [OCamlPro/owi#99]
Hi @filipeom 
With the added patch of https://github.com/formalsec/encoding/pull/50 I get the following error

```
owi: internal error, uncaught exception:
     Failure("Unsupported symbolic value reasoning over \"(++ symbol_0 (++ symbol_0 (++ symbol_0 symbol_0)))\"")
```

Wat file:  
[rust-owi.txt](https://github.com/OCamlPro/owi/files/13941593/rust-owi.txt)

**Comment by filipeom** [comment]
It's trying to `store`/`load` values with a symbolic address. I should have already ported wasp's [memory models](https://github.com/formalsec/wasp-private/tree/memory-refactor/wasp/lib/symbolic/static/memory) here but I haven't had the time :disappointed:. I'll make the symbolic interpreter concretise for now

**Comment by krtab** [comment]
> It's trying to `store`/`load` values with a symbolic address. I should have already ported wasp's [memory models](https://github.com/formalsec/wasp-private/tree/memory-refactor/wasp/lib/symbolic/static/memory) here but I haven't had the time 😞. I'll make the symbolic interpreter concretise for now

Could you give me access to the repo ?

**Comment by filipeom** [comment]
I should have linked the new repo here https://github.com/formalsec/memory-models. But I'll give you access to both

**Comment by krtab** [comment]
Closing in favor of #182
